version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - './src/:/var/www/html'
    ports:
      - '80:80'
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
